# 1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np
Y = np.random.random((3,3,3))
print(Y)

[[[0.96425533 0.03456146 0.76858802]
  [0.42050822 0.75461923 0.08567673]
  [0.3532992  0.36670604 0.23306724]]

 [[0.73788624 0.75363905 0.57866516]
  [0.6147867  0.24313539 0.06340965]
  [0.62686797 0.59166393 0.61492014]]

 [[0.22817838 0.92802179 0.65805762]
  [0.86115327 0.66312055 0.65201094]
  [0.93838048 0.54542687 0.43239917]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.12104826 1.         0.60228712 0.45948521 0.47080175]
 [0.43020695 0.7092612  0.30132789 0.58466716 0.24972803]
 [0.22635524 0.44091546 0.60254667 0.06011252 0.53664063]
 [0.50761367 0.81381968 0.52007581 0.5389879  0.35358223]
 [0.31421343 0.74129197 0.02964858 0.         0.26829144]]


# 5.  How to find common values between two arrays?

In [8]:
Z1 = np.random.randint(0,8,8)
Z2 = np.random.randint(0,8,8)
print(np.intersect1d(Z1,Z2))

[2 3]


# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-08-07
2020-08-08
2020-08-09


# 7. Consider two random array A and B, check if they are equal

In [12]:
A = np.random.randint(0,3,5)
B = np.random.randint(0,3,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [16]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.76179618 0.76136066 0.57048147 0.06821329 0.         0.71281865
 0.34535246 0.119936   0.12519403 0.31697747]


# 9. How to print all the values of an array?

In [13]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((32,32))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 

# 10.Subtract the mean of each row of a matrix

In [14]:
X = np.random.rand(5, 10)


Y = X - X.mean(axis=1, keepdims=True)
print(Y)


[[ 0.44529528 -0.37167168  0.22257542 -0.11275386 -0.42631216  0.19250372
  -0.40833199 -0.1443165   0.20690663  0.39610515]
 [ 0.10456339 -0.02601382 -0.0611454   0.29860826  0.10828619  0.22537678
   0.25586914 -0.22414037 -0.20998703 -0.47141713]
 [ 0.15501939 -0.61367412  0.34856808  0.26757184  0.36057096 -0.11007434
   0.28206612 -0.46126105 -0.53014532  0.30135844]
 [ 0.2072254  -0.27492704 -0.27234675 -0.19537702  0.21565216 -0.12461349
   0.20255687  0.51084351 -0.14580576 -0.12320788]
 [ 0.05141376  0.24265597 -0.15203292  0.36660257 -0.27759588 -0.37679141
   0.1303903  -0.27868434  0.00759155  0.28645039]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [22]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 2. 2. 4. 4. 3. 1. 4. 2. 4.]


In [23]:
np.add.at(Z, I, 1)
print(Z)

[7. 3. 3. 7. 7. 5. 1. 7. 3. 7.]


# 12.How to get the diagonal of a dot product?

In [31]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.58178833 0.76658825 0.61477495 0.12653061 0.86772132]
 [0.46757268 0.38641674 0.80761341 0.25715911 0.45104287]
 [0.73865237 0.4749705  0.06653438 0.99364804 0.34618558]
 [0.68015717 0.59553642 0.01168946 0.06275222 0.9848539 ]
 [0.26216036 0.17066338 0.19331973 0.79120091 0.23940699]]
[[0.57201191 0.46620129 0.90364766 0.812761   0.93358363]
 [0.40040022 0.78733798 0.23231254 0.84865637 0.56652973]
 [0.92603188 0.11353386 0.68349069 0.93702432 0.89356843]
 [0.20652459 0.22272549 0.13153942 0.64420725 0.89934241]
 [0.87464973 0.89226641 0.92996362 0.70392899 0.55025684]]
diagonal of a dot product method 1 is.... [1.99411706 1.07364132 1.2759426  1.80285695 1.35747477]
diagonal of a dot product method 2 is.... [1.99411706 1.07364132 1.2759426  1.80285695 1.35747477]


# 13.How to find the most frequent value in an array?

In [15]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[8 6 4 5 7 7 7 4 8 7 1 8 9 5 9 6 8 9 3 1 3 7 6 8 0 1 9 3 8 5 5 6 8 8 8 2 2
 1 0 4 7 8 6 8 1 7 4 4 1 4]
rank: 8


# 14.How to get the n largest values of an array

In [16]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [17]:
Z = np.array([("Hello", 5.2, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 5.2, 3) (b'World', 3.6, 2)]
